[theme]
base = "light"
backgroundColor = "#FFFFFF"          # 白
secondaryBackgroundColor = "#F6F7FB" # ごく薄いグレー（カード）
textColor = "#0B1220"                # 濃い文字（AA達成）
primaryColor = "#166534"             # ターフグリーン（ボタン/リンク）
font = "sans serif"


st.markdown("""
<style>
:root{
  /* ベース */
  --bg:#FFFFFF; --bg2:#F6F7FB; --text:#0B1220; --muted:#475569;
  --accent:#166534;          /* 芝(ターフ)グリーン */
  --dirt:#8B5E34;            /* ダートブラウン */
  --rail:#E5E7EB;            /* ラチ/白系 */
  --border:#E5E7EB;

  /* 枠色（JRAの枠色に合わせた近似色） */
  --waku-1:#FFFFFF;  --waku-2:#111111;  --waku-3:#DC2626;  --waku-4:#2563EB;
  --waku-5:#FACC15;  --waku-6:#16A34A;  --waku-7:#FB923C;  --waku-8:#F472B6;
}

/* 背景とカード（白ベース＋軽い影でメリハリ） */
section.main{ background:var(--bg); }
[data-testid="stSidebar"]{ background:var(--bg2); }
.block-container > div, .stCard{
  background:#FFF!important; border:1px solid var(--border)!important;
  box-shadow:0 6px 18px rgba(2,6,23,.06), 0 2px 6px rgba(2,6,23,.04);
  border-radius:14px; padding:16px; color:var(--text)!important;
}
h1,h2,h3{ color:var(--text)!important; font-weight:800; letter-spacing:.2px; }

/* コースバッジ（芝/ダート） */
.badge{ display:inline-flex; gap:.4rem; align-items:center; font-weight:700;
  padding:.25rem .6rem; border-radius:999px; border:1px solid var(--border);}
.badge.turf{ background:#ECFDF5; color:var(--accent); }
.badge.dirt{ background:#FEF7EE; color:var(--dirt); }
.badge .dot{ width:.6rem; height:.6rem; border-radius:999px; }
.badge.turf .dot{ background:var(--accent); }
.badge.dirt .dot{ background:var(--dirt); }

/* 枠色ピル（左端に“枠色×馬番”の視覚手がかり） */
.waku{ display:inline-flex; align-items:center; gap:.45rem;
  padding:.35rem .6rem; border-radius:12px; border:1px solid var(--border);
  font-weight:800; }
.w1{ background:var(--waku-1); color:#111; }
.w2{ background:var(--waku-2); color:#FFF; }
.w3{ background:var(--waku-3); color:#FFF; }
.w4{ background:var(--waku-4); color:#FFF; }
.w5{ background:var(--waku-5); color:#111; }
.w6{ background:var(--waku-6); color:#FFF; }
.w7{ background:var(--waku-7); color:#111; }
.w8{ background:var(--waku-8); color:#111; }

/* 進捗/スコア（トラック=ラチ色、バー=芝色） */
div.stProgress>div{ background:var(--rail); height:12px; border-radius:999px; }
div.stProgress>div>div{ background:var(--accent); }

/* 見出し下に“ゲートの芝ライン” */
h2::after{
  content:""; display:block; height:4px; margin:.35rem 0 .8rem;
  background:linear-gradient(90deg,var(--accent) 0 60%, var(--dirt) 60% 100%);
  border-radius:999px;
}

/* オッズ盤（ライト版：薄いアンバー面 × 等幅数字） */
.odds{
  background:#FFF8E1; border:1px solid #FDE68A; border-radius:10px; padding:.6rem .8rem;
  font-variant-numeric: tabular-nums; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  color:#1F2937;
}
</style>
""", unsafe_allow_html=True)
