[theme]
base = "light"
backgroundColor = "#FFFFFF"        # ページ背景（白）
secondaryBackgroundColor = "#F8FAFC"  # カードやサイドの薄グレー
textColor = "#111827"              # ほぼ黒（読みやすい）
primaryColor = "#1D4ED8"           # ボタン/強調（青700：白文字でAA）
font = "sans serif"
