[theme]
base = "light"
backgroundColor = "#FFFFFF"          # 純白
secondaryBackgroundColor = "#F8FAFC" # ごく薄い面（カード/サイド）
textColor = "#0B1220"                # 見出しもいける濃い文字色
primaryColor = "#2563EB"             # アクセント（白字でもAA）
font = "sans serif"


