[theme]
base = "light"
backgroundColor = "#FFFFFF"          # 白
secondaryBackgroundColor = "#F6F7FB" # ごく薄いグレー（カード）
textColor = "#0B1220"                # 濃い文字（AA達成）
primaryColor = "#166534"             # ターフグリーン（ボタン/リンク）
font = "sans serif"


