[theme]
base = "light"
primaryColor = "#3B82F6"            # 明るめのブルー（アクセント）
backgroundColor = "#F8FAFC"         # ほぼ白（ページ背景）
secondaryBackgroundColor = "#FFFFFF" # 真っ白（カード/コンテナ）
textColor = "#334155"               # スレート系の濃グレー（読みやすい）
font = "sans serif"
